[package]
name = "SUSTech_CS323_Project_Incredibuild"
version = "0.1.0"

[workspace]
members = [
    "src/lexer",
]

[dependencies]
logos = "0.14.2"
lalrpop = { version = "0.22.0", default-features = false }
llvm-ir = { version = "0.11.1", features = ["llvm-17"] }
