[package]
name = "SUSTech_CS323_Project_Incredibuild"
version = "0.1.0"
edition = "2021"

[workspace]
members = [ "src/ast",
    "src/lexer",
    "src/parser",
    "src/ast"
]

[dependencies]
logos = "0.14.2"
lalrpop = { version = "0.22.0", default-features = false }
llvm-ir = { version = "0.11.1", features = ["llvm-17"] }
