[package]
name = "spl_analyser"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"

[dependencies]
spl_lexer = {version = "0.0.1", path = "../lexer"}
spl_ast = {version = "0.0.1", path = "../ast"}
spl_parser = {version = "0.0.1", path = "../parser"}
thiserror = "2"
