name: Test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "17.0"

    - name: Test Lexer
      run: cargo test --verbose
      working-directory: src/lexer

    - name: Test Parser
      run: cargo test --verbose
      working-directory: src/parser

    - name: Test Analyzer
      run: cargo test --verbose
      working-directory: src/analyser

    - name: Test IRGen
      run: cargo test --verbose
      working-directory: src/irgen

    - name: Test CodeGen
      run: for file in test/phase4/*.spl; do cargo run -- $file; cc `echo $file | sed 's/\.spl/\.S/'` -o $file.out; done