name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Test Parser
      run: cargo test --verbose
      working-directory: src/parser

    - name: Test Lexer
      run: cargo test --verbose
      working-directory: src/lexer
